# Generated by Django 4.2.17 on 2024-12-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_currencydata_delete_currencyrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrentCrudeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='currencydata',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='close_price',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='high_price',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='low_price',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='open_price',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='volume',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
